name: "EIP Board"
description: "Generate list of pull requests that need attention"

inputs:
  path:
    description: "Where to place the generated HTML"
    required: true
  extra_args:
    description: "Extra arguments to pass to eip-board"
    required: false
  repository:
    description: "Override the repository being analyzed"
    required: false

runs:
  using: "composite"
  steps:
      - name: Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84
        with:
          cache-targets: false

      - name: Install EIP Board
        shell: bash
        run: cargo install --locked --path "${{ github.action_path }}"

      - name: Generate List
        id: eip-board
        shell: bash
        run: |
          mkdir -p "$(dirname "$INPUT_PATH")"
          export GITHUB_REPOSITORY="${REPOSITORY:-$GITHUB_REPOSITORY}"
          eip-board ${{ inputs.extra_args }} > "$INPUT_PATH"
        env:
          INPUT_PATH: ${{ inputs.path }}
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ inputs.repository }}
